const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const doc = {
	info: {
		version: process.version,
		title: 'REST API for Express E-commerce API',
		description:
			'Documentation automatically generated by the <b>swagger-autogen</b> module.',
	},
	host: 'localhost:3000',
	basePath: '/',
	schemes: ['http', 'https'],
	consumes: ['application/json'],
	produces: ['application/json'],
	securityDefinitions: {
		api_key: {
			type: 'apiKey',
			name: 'api_key',
			in: 'header',
		},
	},
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/index.ts'];

swaggerAutogen(outputFile, endpointsFiles);
